In [65]:
import pandas as pd

In [66]:
df=pd.read_excel("Decathlon Apparel Data main.xlsx")

In [67]:
df

,product_name,brand,star_rating,number_of_reviews,MRP(in rs),MRP,sale_price(in rs),sale_price,colour,description,Quantity,amount,transaction_Id,transaction date,User_ID,Cust_name,Gender,Age
0,100 Base Layer Ski Pants Women's,Wedze,4.4,3101,836.2629,9.99,836.2629,9.99,Black,"[""100 Base Layer Ski Pants Women's | Designed ...",3,2508.7887,156752,2022-05-01,1002903,Sanskriti,F,28
1,Thermal Underwear Base Layer Top Women's,Wedze,4.5,7367,836.2629,9.99,669.6800,8.00,Black,"[""Thermal Underwear Base Layer Top Women's | D...",2,1339.3600,156753,2022-05-02,1000732,Kartik,F,35
2,100 Ski Jacket Men's,Wedze,4.6,3798,3347.5629,39.99,2511.3000,30.00,Black,"[""100 Ski Jacket Men's | This warm and comfort...",1,2511.3000,156754,2022-05-03,1001990,Bindu,F,35
3,Forclaz Trek 500 Merino Wool Hiking Hat Adult,Forclaz,4.6,1803,2091.9129,24.99,2091.9129,24.99,Whale Gray,['Forclaz Trek 500 Merino Wool Hiking Hat Adul...,1,2091.9129,156755,2022-05-04,1001425,Sudevi,M,16
4,Wedze FR100 Freeride Ski Jacket Women's,Wedze,4.5,239,9961.4900,119.00,5859.7000,70.00,Light Gray,"[""Wedze FR100 Freeride Ski Jacket Women's | Ou...",3,17579.1000,156756,2022-05-05,1000588,Joni,M,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,"MH K100, Category 3 Hiking Sunglasses, Kids'",Quechua,4.6,1307,1087.3929,12.99,669.6800,8.00,Blush Pink,"[""MH K100, Category 3 Hiking Sunglasses, Kids'...",2,1339.3600,157386,2024-01-25,1004682,Vishakha,F,27
635,Women's Cardio Training Fitness Shoes Mid 120,Domyos,4.4,1691,2929.0129,34.99,2092.7500,25.00,Black,"[""Women's Cardio Training Fitness Shoes Mid 12...",1,2092.7500,157387,2024-01-26,1004791,Crebagga,F,19
636,Keepdry 100 Long-Sleeved Soccer Base Layer Top ',Kipsta,4.7,1483,1087.3929,12.99,418.5500,5.00,Bright Indigo,"[""Keepdry 100 Long-Sleeved Soccer Base Layer T...",3,1255.6500,157388,2024-01-27,1002181,Sweta,F,32
637,Adult Football Bottoms Essential - Black,Kipsta,4.6,705,2091.9129,24.99,1255.6500,15.00,Black,['Adult Football Bottoms Essential - Black | O...,2,2511.3000,157389,2024-01-28,1002109,Gelder,F,34
638,Boys' Gym Tracksuit Warm Breathable Synthetic ...,Domyos,4.5,672,2091.9129,24.99,1255.6500,15.00,Black,"[""Boys' Gym Tracksuit Warm Breathable Syntheti...",1,1255.6500,157390,2024-01-29,1001563,Subhasmita,M,16

# dropping unnecessary columns

In [68]:
df=df.drop(columns=['colour', 'number_of_reviews','sale_price','description'])

In [69]:
df

,product_name,brand,star_rating,MRP(in rs),MRP,sale_price(in rs),Quantity,amount,transaction_Id,transaction date,User_ID,Cust_name,Gender,Age
0,100 Base Layer Ski Pants Women's,Wedze,4.4,836.2629,9.99,836.2629,3,2508.7887,156752,2022-05-01,1002903,Sanskriti,F,28
1,Thermal Underwear Base Layer Top Women's,Wedze,4.5,836.2629,9.99,669.6800,2,1339.3600,156753,2022-05-02,1000732,Kartik,F,35
2,100 Ski Jacket Men's,Wedze,4.6,3347.5629,39.99,2511.3000,1,2511.3000,156754,2022-05-03,1001990,Bindu,F,35
3,Forclaz Trek 500 Merino Wool Hiking Hat Adult,Forclaz,4.6,2091.9129,24.99,2091.9129,1,2091.9129,156755,2022-05-04,1001425,Sudevi,M,16
4,Wedze FR100 Freeride Ski Jacket Women's,Wedze,4.5,9961.4900,119.00,5859.7000,3,17579.1000,156756,2022-05-05,1000588,Joni,M,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,"MH K100, Category 3 Hiking Sunglasses, Kids'",Quechua,4.6,1087.3929,12.99,669.6800,2,1339.3600,157386,2024-01-25,1004682,Vishakha,F,27
635,Women's Cardio Training Fitness Shoes Mid 120,Domyos,4.4,2929.0129,34.99,2092.7500,1,2092.7500,157387,2024-01-26,1004791,Crebagga,F,19
636,Keepdry 100 Long-Sleeved Soccer Base Layer Top ',Kipsta,4.7,1087.3929,12.99,418.5500,3,1255.6500,157388,2024-01-27,1002181,Sweta,F,32
637,Adult Football Bottoms Essential - Black,Kipsta,4.6,2091.9129,24.99,1255.6500,2,2511.3000,157389,2024-01-28,1002109,Gelder,F,34
638,Boys' Gym Tracksuit Warm Breathable Synthetic ...,Domyos,4.5,2091.9129,24.99,1255.6500,1,1255.6500,157390,2024-01-29,1001563,Subhasmita,M,16

In [70]:
df.info

<bound method DataFrame.info of                                           product_name    brand  star_rating  \
0                     100 Base Layer Ski Pants Women's    Wedze          4.4
1             Thermal Underwear Base Layer Top Women's    Wedze          4.5
2                                 100 Ski Jacket Men's    Wedze          4.6
3        Forclaz Trek 500 Merino Wool Hiking Hat Adult  Forclaz          4.6
4              Wedze FR100 Freeride Ski Jacket Women's    Wedze          4.5
..                                                 ...      ...          ...
634       MH K100, Category 3 Hiking Sunglasses, Kids'  Quechua          4.6
635      Women's Cardio Training Fitness Shoes Mid 120   Domyos          4.4
636   Keepdry 100 Long-Sleeved Soccer Base Layer Top '   Kipsta          4.7
637           Adult Football Bottoms Essential - Black   Kipsta          4.6
638  Boys' Gym Tracksuit Warm Breathable Synthetic ...   Domyos          4.5

     MRP(in rs)     MRP  sale_price(in rs)  Quantity      amount  \
0      836.2629    9.99           836.2629         3   2508.7887
1      836.2629    9.99           669.6800         2   1339.3600
2     3347.5629   39.99          2511.3000         1   2511.3000
3     2091.9129   24.99          2091.9129         1   2091.9129
4     9961.4900  119.00          5859.7000         3  17579.1000
..          ...     ...                ...       ...         ...
634   1087.3929   12.99           669.6800         2   1339.3600
635   2929.0129   34.99          2092.7500         1   2092.7500
636   1087.3929   12.99           418.5500         3   1255.6500
637   2091.9129   24.99          1255.6500         2   2511.3000
638   2091.9129   24.99          1255.6500         1   1255.6500

     transaction_Id transaction date  User_ID   Cust_name Gender  Age
0            156752       2022-05-01  1002903   Sanskriti      F   28
1            156753       2022-05-02  1000732      Kartik      F   35
2            156754       2022-05-03  1001990       Bindu      F   35
3            156755       2022-05-04  1001425      Sudevi      M   16
4            156756       2022-05-05  1000588        Joni      M   28
..              ...              ...      ...         ...    ...  ...
634          157386       2024-01-25  1004682    Vishakha      F   27
635          157387       2024-01-26  1004791    Crebagga      F   19
636          157388       2024-01-27  1002181       Sweta      F   32
637          157389       2024-01-28  1002109      Gelder      F   34
638          157390       2024-01-29  1001563  Subhasmita      M   16

[639 rows x 14 columns]>

# feature engineering

we need to create columns for checking the recency(time since last purchase)frequency(number of purchases) and monetary
(total amount spent)value of customers

In [71]:
#convert transaction date to date and time format
df["transaction date"]=pd.to_datetime(df["transaction date"])

In [72]:
#defining reference date for calculation recency
reference_date =df['transaction date'].max()
reference_date

Timestamp('2024-01-29 00:00:00')

In [73]:
recency_df = df.groupby('User_ID')['transaction date'].max().reset_index()
recency_df.columns = ['User_ID','last_purchase_date']
recency_df['recency'] = (reference_date -recency_df['last_purchase_date']).dt.days

In [74]:
#Frequency. Calcolate the total number of transactions per customer
frequency_df = df.groupby('User_ID').size().reset_index()
frequency_df.columns = ['User_ID', 'frequency']

In [75]:
monetary_df = df.groupby('User_ID')['amount'].sum().reset_index()
monetary_df.columns = ['User_ID','monetary']

In [76]:
rfm_df = recency_df.merge(frequency_df, on='User_ID').merge(monetary_df, on='User_ID')

In [77]:
df =df.merge(rfm_df,  on='User_ID' , how='left')

In [79]:
df=df.drop(columns=['last_purchase_date'])

In [80]:
df

,product_name,brand,star_rating,MRP(in rs),MRP,sale_price(in rs),Quantity,amount,transaction_Id,transaction date,User_ID,Cust_name,Gender,Age,recency,frequency,monetary
0,100 Base Layer Ski Pants Women's,Wedze,4.4,836.2629,9.99,836.2629,3,2508.7887,156752,2022-05-01,1002903,Sanskriti,F,28,638,1,2508.7887
1,Thermal Underwear Base Layer Top Women's,Wedze,4.5,836.2629,9.99,669.6800,2,1339.3600,156753,2022-05-02,1000732,Kartik,F,35,16,2,5106.3100
2,100 Ski Jacket Men's,Wedze,4.6,3347.5629,39.99,2511.3000,1,2511.3000,156754,2022-05-03,1001990,Bindu,F,35,636,1,2511.3000
3,Forclaz Trek 500 Merino Wool Hiking Hat Adult,Forclaz,4.6,2091.9129,24.99,2091.9129,1,2091.9129,156755,2022-05-04,1001425,Sudevi,M,16,635,1,2091.9129
4,Wedze FR100 Freeride Ski Jacket Women's,Wedze,4.5,9961.4900,119.00,5859.7000,3,17579.1000,156756,2022-05-05,1000588,Joni,M,28,633,2,40178.2887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,"MH K100, Category 3 Hiking Sunglasses, Kids'",Quechua,4.6,1087.3929,12.99,669.6800,2,1339.3600,157386,2024-01-25,1004682,Vishakha,F,27,4,2,6360.2858
635,Women's Cardio Training Fitness Shoes Mid 120,Domyos,4.4,2929.0129,34.99,2092.7500,1,2092.7500,157387,2024-01-26,1004791,Crebagga,F,19,3,1,2092.7500
636,Keepdry 100 Long-Sleeved Soccer Base Layer Top ',Kipsta,4.7,1087.3929,12.99,418.5500,3,1255.6500,157388,2024-01-27,1002181,Sweta,F,32,2,2,2929.8500
637,Adult Football Bottoms Essential - Black,Kipsta,4.6,2091.9129,24.99,1255.6500,2,2511.3000,157389,2024-01-28,1002109,Gelder,F,34,1,3,28126.5600
638,Boys' Gym Tracksuit Warm Breathable Synthetic ...,Domyos,4.5,2091.9129,24.99,1255.6500,1,1255.6500,157390,2024-01-29,1001563,Subhasmita,M,16,0,1,1255.6500

In [81]:
df.to_csv("decathlon_clean.csv",index=False)